version: '3.8'
services:
  redis:
    # macOS用
    platform: linux/amd64
    image: redis
    restart: always
    ports:
      - '6379:6379'
  worker:
    # macOS用
    platform: linux/amd64
    # appと同じイメージを使う
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    restart: always
    environment:
      RQ_REDIS_URL: redis://redis
    command: rq worker
    volumes:
      - ./exportdir:/app/exportdir
      - ./synology_drive_point:/app/m_synology_drive_point
    working_dir: /app
  app:
    # macOS用
    platform: linux/amd64
    container_name: msm-gas-prepare
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - worker
    restart: always
    tty: true
    command: python chatapp.py
    environment:
      RQ_REDIS_URL: redis://redis
      SESSION_REDIS_URL: redis://redis/10
    volumes:
      - ./exportdir:/app/exportdir
      - ./synology_drive_point:/app/m_synology_drive_point
    ports:
      - "18081:18081"
      - "8080:8080"
    