version: '3.8'
services:
  redis:
    # macOS用
    platform: linux/amd64
    image: redis
  worker:
    # macOS用
    platform: linux/amd64
    # appと同じイメージを使う
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      RQ_REDIS_URL: redis://redis
    command: rq worker
    volumes:
      - .:/app
    working_dir: /app
  app:
    # macOS用
    platform: linux/amd64
    container_name: msm-gas-prepare
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true
    environment:
      RQ_REDIS_URL: redis://redis
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - '18081:18081'
      - '8080:8080'
