version: '3.8'
services:
  redis:
    # macOS用
    platform: linux/amd64
    image: redis
  worker:
    # macOS用
    platform: linux/amd64
    # appと同じイメージを使う
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      RQ_REDIS_URL: redis://redis
    command: rq worker
    volumes:
      - .:/app
    working_dir: /app
  app:
    # macOS用
    platform: linux/amd64
    container_name: msm-gas-prepare
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - worker
    restart: always
    tty: true
    command: python chatapp.py
    environment:
      RQ_REDIS_URL: redis://redis
    volumes:
      - type: volume
        source: exportdir
        target: /app/exportdir
      - type: volume
        source: synology_drive_point
        target: /app/m_synology_drive_point
    ports:
      - "18081:18081"
      - "8080:8080"
    
volumes:
  exportdir:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.35.18,rw
      device: ":/volume1/msm-gas-prepare-dktest/"
  synology_drive_point:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.35.18,rw
      device: ":/volume1/sny-workdir/作業用共有フォルダ/"
