version: '3.8'
services:
  msmgasprepare:
    # macOS用
    platform: linux/amd64
    # 既存のDockerfileを呼び出す
    container_name: msm-gas-prepare
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    tty: true

    # ボリュームマウントをする。NFSを使う。ChatGPTで適当に作ってもらったから、あとで精査する
    volumes:
      - type: bind
        source: ./
        target: /app
    ports:
      - '18081:18081'
      - '8080:8080'
    # 環境変数どうしよう？
