[general]
## ここでは二つ以上で参照する値を設定する

# スケジュール表のスプレッドシートID
# https://docs.google.com/spreadsheets/d/[シートID]
SCHEDULE_SPREADSHEET_ID = "[シートID]"
# スケジュール表の範囲先
SCHEDULE_SPREADSHEET_TABLE_RANGE = "[シート名]![範囲]"

# [generate_quotes, generate_invoiceで利用]
# 見積書、請求書へ記載する会社名
TORIHIKISAKI_NAME = ""

[google]
# 2025-01-16 認証情報のパスはenv側へ移動しました
# スペース名を記載します。スペースの設定から確認できます。
CHAT_SPACENAME = "spaces/[space name]"


[run_mail_action]
# ボイラープレート向け
MSM_GAS_BOILERPLATE_PATH = ""
# ボイラープレートから生成してファイルなどを準備したプロジェクトフォルダの保存先
COPY_PROJECT_DIR_DEST_PATH = ""

# 見積計算表のテンプレート:ID
# https://docs.google.com/spreadsheets/d/[シートID]
ESTIMATECALC_TEMPLATE_GSHEET_ID = "[シートID]"

# 連絡項目表ファイルを一時保存するGoogleドライブのフォルダID
# https://drive.google.com/drive/folders/[フォルダID]
RENRAKUKOUMOKU_SAVE_DIR_IDS = ["[フォルダID]"]

# 入金日の日の基準日: 数字
NYUKIN_STANDARD_DAY = 20

[generate_quotes]
# 見積計算の保存先
# https://drive.google.com/drive/folders/[フォルダID]
ESTIMATE_CALCSHEET_DIR_IDS = ["[フォルダID]"]

# 見積計算表のPDF生成をした後の生成前シート保存先
# https://drive.google.com/drive/folders/[フォルダID]
ARCHIVED_ESTIMATECALCSHEET_DIR_IDS = "[フォルダID]"

# 見積書生成:
# 見積書のファイル一覧を記録するGoogleスプレッドシートのID
# https://docs.google.com/spreadsheets/d/[シートID]
QUOTE_FILE_LIST_GSHEET_ID = "[シートID]"
# GoogleスプレッドシートのテンプレートID
# https://docs.google.com/spreadsheets/d/[シートID]
QUOTE_TEMPLATE_GSHEET_ID = "[シートID]"
# テンプレートに入力するセルマッピング・JSONファイルのパス
QUOTE_TEMPLATE_CELL_MAPPING_JSON = "json path"
# 見積書の保存先
# https://drive.google.com/drive/folders/[フォルダID]
QUOTE_SAVE_DIR_IDS = ["[フォルダID]"]

mail_template_body = """
メールテンプレートです
納期置き換えテスト{{nouki}}

---

ここに署名が入ります
"""

[generate_invoice]
# 請求書生成:
# 請求書のファイル一覧を記録するGoogleスプレッドシートのID
# https://docs.google.com/spreadsheets/d/[シートID]
INVOICE_FILE_LIST_GSHEET_ID = "[シートID]"
# GoogleスプレッドシートのテンプレートID
# https://docs.google.com/spreadsheets/d/[シートID]
INVOICE_TEMPLATE_GSHEET_ID = "[シートID]"
# テンプレートに入力するセルマッピング・JSONファイルのパス
INVOICE_TEMPLATE_CELL_MAPPING_JSON = "json path"
# 請求書の保存先
# https://drive.google.com/drive/folders/[フォルダID]
INVOICE_SAVE_DIR_IDS = ["[フォルダID]"]

mail_to = ""
mail_cc = ""
mail_template_title = "{{datetime}} 請求書送付について"
mail_template_body = """

請求書のテスト用テンプレです。

---

ここに署名が入ります
"""
