[general]
## ここでは二つ以上で参照する値を設定する

# スケジュール表のスプレッドシートID
# https://docs.google.com/spreadsheets/d/[シートID]
SCHEDULE_SPREADSHEET_ID = "[シートID]"
# スケジュール表の範囲先
SCHEDULE_SPREADSHEET_TABLE_RANGE = "[シート名]![範囲]"

# [generate_quotes, get_billingで利用]
# 見積書、請求書へ記載する会社名
TORIHIKISAKI_NAME = ""

[google]
GMAIL_USER_ID = "me"
CRED_FILEPATH = "json path"
CHAT_SA_CRED_FILEPATH = "json path"
# スペース名を記載します。スペースの設定から確認できます。
CHAT_SPACENAME = "spaces/[space name]"

# 2024-02-01 このセクションは今後利用しないので、除去予定。
[mfci]
# 取引先IDの取得方法: 取引先一覧 -> そのIDではなく、そのID -> 取引先取得 -> relationships>departments>data>id が取引先ID
# 法人側乗り換えで登録した取引先ID
TORIHIKISAKI_ID = ""

# 認証情報 法人側 v3
MFCLOUD_CLIENT_ID = ""
MFCLOUD_CLIENT_SECRET = ""

# APIで一度に取得するデータ件数
QUOTE_PER_PAGE = 100

[run_mail_action]
# ボイラープレート向け
MSM_GAS_BOILERPLATE_PATH = ""
# ボイラープレートから生成してファイルなどを準備したプロジェクトフォルダの保存先
COPY_PROJECT_DIR_DEST_PATH = ""

# 見積計算表のテンプレート:ID
# https://docs.google.com/spreadsheets/d/[シートID]
ESTIMATECALC_TEMPLATE_GSHEET_ID = "[シートID]"

# 連絡項目表ファイルを一時保存するGoogleドライブのフォルダID
# https://drive.google.com/drive/folders/[フォルダID]
RENRAKUKOUMOKU_SAVE_DIR_IDS = ["[フォルダID]"]

# 入金日の日の基準日: 数字
NYUKIN_STANDARD_DAY = 20

[generate_quotes]
# 見積計算の保存先
# https://drive.google.com/drive/folders/[フォルダID]
ESTIMATE_CALCSHEET_DIR_IDS = ["[フォルダID]"]

# 見積計算表のPDF生成をした後の生成前シート保存先
# https://drive.google.com/drive/folders/[フォルダID]
ARCHIVED_ESTIMATECALCSHEET_DIR_IDS = "[フォルダID]"

# 見積書生成:
# 見積書のファイル一覧を記録するGoogleスプレッドシートのID
# https://docs.google.com/spreadsheets/d/[シートID]
QUOTE_FILE_LIST_GSHEET_ID = "[シートID]"
# GoogleスプレッドシートのテンプレートID
# https://docs.google.com/spreadsheets/d/[シートID]
QUOTE_TEMPLATE_GSHEET_ID = "[シートID]"
# テンプレートに入力するセルマッピング・JSONファイルのパス
QUOTE_TEMPLATE_CELL_MAPPING_JSON = "json path"
# 見積書の保存先
# https://drive.google.com/drive/folders/[フォルダID]
QUOTE_SAVE_DIR_IDS = ["[フォルダID]"]

mail_template_body = """
メールテンプレートです
納期置き換えテスト{{nouki}}

---

ここに署名が入ります
"""

[get_billing]
# 請求書生成:
# 請求書のファイル一覧を記録するGoogleスプレッドシートのID
# https://docs.google.com/spreadsheets/d/[シートID]
INVOICE_FILE_LIST_GSHEET_ID = "[シートID]"
# GoogleスプレッドシートのテンプレートID
# https://docs.google.com/spreadsheets/d/[シートID]
INVOICE_TEMPLATE_GSHEET_ID = "[シートID]"
# テンプレートに入力するセルマッピング・JSONファイルのパス
INVOICE_TEMPLATE_CELL_MAPPING_JSON = "json path"
# 請求書の保存先
# https://drive.google.com/drive/folders/[フォルダID]
INVOICE_SAVE_DIR_IDS = ["[フォルダID]"]

mail_to = ""
mail_cc = ""
mail_template_title = "{{datetime}} 請求書送付について"
mail_template_body = """

請求書のテスト用テンプレです。

---

ここに署名が入ります
"""

[send_sagakusyoumei]
MSM_PROSUGATE_ID = ""
MSM_PROSUGATE_PASS = ""

# https://docs.google.com/spreadsheets/d/[シートID]
TEMPLATE_SHEET_ID = "[シートID]"

MAIL_TO = ""
MAIL_CC = ""
MAIL_TEMPLATE_TITLE = "test 売掛金勘定差額明細書（請求書）送付について"
MAIL_TEMPLATE_BODY = """

{{billing_year}}年{{billing_month}}月の売掛金勘定差額明細書のメールテスト用です

---

ここに署名が入ります
"""

[other]
# スケジュール表更新用に収集するデータのフォルダ
# HAKIAN_PROJECT_DIRPATH = "Z:/00_取引先一覧/80ミスミ「ガススプリング配管図」/1 配管図/2022/"
